import Foundation
import AppKit

/// Opens a terminal window running Claude Code under a chosen config dir.
///
/// ClaudeSwitch never mutates ~/.claude or the keychain to "switch" accounts — it only
/// sets CLAUDE_CONFIG_DIR for the window it opens. Two details matter:
///
///  * `open` passes the launching process's environment through to the child,
///    so a stale CLAUDE_CONFIG_DIR would silently override us. The generated
///    script always sets the variable explicitly, and *unsets* it for the
///    default profile.
///  * Ghostty ignores --working-directory when invoked via `open --args`, so the
///    script cd's for itself.
enum Launcher {

    /// Scripts are named from the config dir, not the display name, so renaming
    /// a profile doesn't orphan its script.
    static func scriptSlug(for profile: Profile) -> String {
        Discovery.derivedName(for: profile.configDir)
            .replacingOccurrences(of: "[^A-Za-z0-9_-]", with: "-", options: .regularExpression)
    }

    /// Deletes launch scripts left behind by profiles that no longer exist.
    static func pruneScripts(keeping profiles: [Profile]) {
        let keep = Set(profiles.map { "\(scriptSlug(for: $0)).command" })
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(atPath: Paths.launchScripts.path)
        else { return }
        for file in files where file.hasSuffix(".command") && !keep.contains(file) {
            try? fm.removeItem(at: Paths.launchScripts.appendingPathComponent(file))
        }
    }

    /// Writes the launch script for a profile and returns its path.
    static func writeScript(for profile: Profile, prefs: Prefs, overrideCommand: String? = nil) throws -> String {
        try FileManager.default.createDirectory(at: Paths.launchScripts, withIntermediateDirectories: true)

        let url = Paths.launchScripts.appendingPathComponent("\(scriptSlug(for: profile)).command")

        let workdir = profile.workingDir ?? NSHomeDirectory()
        var payload = overrideCommand ?? profile.command
        if prefs.keepShellOpen {
            payload += "; echo; echo \"[claudeswitch] \(profile.name) session ended\"; exec /bin/zsh -i"
        }

        // Clear inherited session markers first, then set the profile's config
        // dir — order matters, or we'd unset what we just set.
        let clearMarkers = "unset " + claudeSessionMarkers.joined(separator: " ")
        let envLine = profile.isDefault
            ? "unset CLAUDE_CONFIG_DIR"
            : "export CLAUDE_CONFIG_DIR=\(shellQuote(profile.configDir))"

        let script = """
        #!/bin/zsh
        # Generated by ClaudeSwitch. Rewritten on every launch — edit the profile, not this file.
        # Profile: \(profile.name)   Config: \(profile.shortDir)
        \(clearMarkers)
        \(envLine)
        cd \(shellQuote(workdir)) 2>/dev/null || cd "$HOME"
        exec /bin/zsh -i -c \(shellQuote(payload))
        """

        try script.write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
        return url.path
    }

    /// Opens the script in the configured terminal.
    @discardableResult
    static func launch(_ profile: Profile, prefs: Prefs, overrideCommand: String? = nil) -> String? {
        let script: String
        do { script = try writeScript(for: profile, prefs: prefs, overrideCommand: overrideCommand) }
        catch { return "could not write launch script: \(error.localizedDescription)" }

        var term = prefs.terminal
        if !term.isInstalled {
            guard let fallback = TerminalApp.installed.first else { return "no terminal app found" }
            term = fallback
        }

        let result: RunResult
        switch term {
        case .ghostty:
            // Ghostty on macOS only accepts arguments through `open --args`.
            result = run("/usr/bin/open", ["-na", term.bundlePath, "--args", "-e", script])
        case .terminal, .iterm:
            // Both run an executable .command file in a fresh window.
            result = run("/usr/bin/open", ["-a", term.bundlePath, script])
        case .warp, .kitty:
            result = run("/usr/bin/open", ["-na", term.bundlePath, "--args", script])
        }
        return result.ok ? nil : (result.stderr.isEmpty ? "launch failed" : result.stderr)
    }

    /// Runs the interactive login flow for a config dir in a terminal window.
    static func signIn(_ profile: Profile, prefs: Prefs) -> String? {
        launch(profile, prefs: prefs, overrideCommand: "command claude /login")
    }

    static func revealInFinder(_ path: String) {
        NSWorkspace.shared.selectFile(nil, inFileViewerRootedAtPath: path)
    }
}
